### ISSUE TITLE
Not connecting to MySQL Server, Error 111

### ISSUE THREAD

**Issue by TopherIII** [FredyH/MySQLOO#82] opened 2021-04-12 13:20 UTC
Hi,
I have tried every possible fix for this error that I could find, absolutely nothing has even come close to working.
We are running the gameserver and the SQL host on a Dedi.

the details for the Dedi are as follows:

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

mysqladmin  Ver 8.42 Distrib 5.7.33, for Linux on x86_64

We are using Wisp (which is hosted externally) as a panel for the server.

So far we have tried:
- Reassigning the mysql socket (listening IP/Port)
- Ensuring that we have set file correct file permissions for all SQL files
- Tested that the firewall is not affecting the connection
- Changing mysql user access protocols
- Many others that I cannot recall

I understand that we are running an old version of Ubuntu on the Dedi and that this may be the entire issue. I am looking for a way to fix this error without having to reinstall the OS as we have many files and other game servers on the Dedi.

I'm hoping that you are able to help me with this issue.

**Comment by viral32111** [comment] 2021-04-12 14:05
Error 111 is connection refused, I'm going to assume the the game server and mysql daemon is running on the same machine since you said they were on a dedicated server, which means you're either connecting via loopback or through the mysqld unix domain  socket, both of which shouldn't be affected by a firewall at all.

If you're connecting via unix domain socket, make sure the socket has permissions `srwxrwxrwx` so that the user for the game server process has permissions to read, write and execute on the socket, i.e. `777` (the execute bit is needed for connecting, and i'm going to assume read is needed to actually see it and write is needed to send/receive). The mysql daemon should be creating the socket with these permissions by default anyway though.

If you're connecting via loopback, i.e. `127.0.0.1`, then use ss or netstat to ensure the mysql daemon is actually listening on the correct IP address, and that you have specified the exact same IP address in this module's `connect()` call. Make sure the port numbers also match up, the default port is `3306` for regular sql queries/traffic and `33060` for the shell/mysqlx. Never specify `localhost` as the listening host or connecting host, another process on the system could be catching or filtering traffic on it by remapping entries in the hosts file/nameserver responder, and it might never reach the mysql daemon.

You didn't say this, but just in case, if you're running the game server or mysql daemon in some sort of container, such as docker, then ensure the container's are networked to the host, or two each other and that the corrisponding ports and IP addresses are correctly published/exposed.

It shouldn't be a mysql user host field issue because then at least you would be able to connect, it would just immeditely kick you for not establishing the connection from whatever host that user requires. Just in case though, try set the host to the wildcard `%` i suppose.

If none of this works then try looking at the mysql logs, usually in `/var/log/mysql/`, it might be logging some errors/warnings that are the cause of it not accepting the connections. You could also try connecting from something else other than a game server, such as a quick python/node.js script, which might identify if the issue is it not allowing anything to connect or if for some reason its just the game server process.

**Comment by FredyH** [comment] 2021-04-23 20:58
I'm closing this, if the issue persists, please feel free to reopen.

**Closed by FredyH** 2021-04-23 20:58 UTC
