### ISSUE TITLE
Server Crash on Map Change

### ISSUE THREAD

**Issue by SkyMulley** [FredyH/MySQLOO#45] opened 2020-02-27 16:11 UTC
Follow up reference in #37 . I've noticed this come up quite a lot recently around server owners. I've gone ahead and spent some time trying to replicate the issue and have found a case where the server crashes on map change. It seems to only happen with some addons over others (Eg. DarkRP runs fine, GmodAdminSuite crashes).

Can't re-open issues so had to post a new one, sorrie about that.
32 bit (I believe), Linux Server

**Comment by VindoesCompooter** [comment] 2020-02-27 16:20
Changing the version to an earlier version fixed it for me, unsure as to which version I used.

**Comment by Maldevelops** [comment] 2020-03-22 21:44
Changing to an earlier version doesn't work for more recent addons.

**Comment by FredyH** [comment] 2020-03-22 22:41
So you are saying it crashes even with an older version of mysqloo when you change the map?

**Comment by SkyMulley** [comment] 2020-03-22 22:42
I'm using an older version of MySQLOO and the crashes do not occur during map changes, however with the latest it does.

**Comment by VindoesCompooter** [comment] 2020-03-23 16:57
@FredyH Same issue, essentially we had to switch to an older version to allow map changes since we use map changes a lot with our server events. However this meant that ServerGuard would no longer record bans properly.

**Comment by FredyH** [comment] 2020-03-23 17:27
This seems to be related to certain addons that might run queries right as the server reloads, could you post what addons you have installed on your server that use mysql?

**Comment by VindoesCompooter** [comment] 2020-03-23 18:11
We're using Helix as a gamemode, and ServerGuard as an admin system.

**Comment by Maldevelops** [comment] 2020-04-01 16:50
This is what happens on change level - https://gyazo.com/09cc9dee7f0dc5807684481a80ff646c

It does look like [GmodAdminSuite ](https://steamcommunity.com/sharedfiles/filedetails/?id=1595332211)seems to be contacting the database right before the changelevel and causes the crash to occur.

**Comment by FredyH** [comment] 2020-04-01 20:26
Ah this is actually really helpful, it seems the issue is rather that it runs SQL instantly when the server starts after the map change.

**Comment by Maldevelops** [comment] 2020-04-02 21:56
So that means that GmodAdminSuite is the offender in this case or is there a possible fix within mysqloo?

**Comment by G-Force007** [comment] 2020-04-12 10:52
Confirmed crashes, even with delays added.

I've delayed my mysql queries from running 20-30 seconds after map change, and it still continues to crash. I'd love to continue using 9.5 but because I'm planning on utilising windows 64 beta there is no support there.

**Comment by FredyH** [comment] 2020-04-12 10:56
Could you send me exactly the script you ran that  makes the server crash every time? That would help me debug this issue immensely.

**Comment by G-Force007** [comment] 2020-04-12 11:08
It's basically my gamemodes functionality. I'd have to strip it out and make a single file. I'll work on this one.

Going through some of your recent changes I also noticed that some files are out of date:
https://github.com/Facepunch/gmod-module-base/blob/development/include/GarrysMod/Lua/Types.h
vs
https://github.com/FredyH/MySQLOO/blob/master/GmodLUA/include/GarrysMod/Lua/Types.h

**Comment by G-Force007** [comment] 2020-04-12 11:19
Minidump crash files indicate below:
===

Exception Code: 0xC0000005
Exception Information: The thread tried to read from or write to a virtual address for which it does not have the appropriate access.

**Comment by willox** [comment] 2020-04-12 14:59
The relevant stack trace to G-Force's crashes is below. It doesn't tell me much other than that somehow the Lua state's garbage collector has been left in an invalid state? I don't know how i'd even go about trying to reproduce this crash with a binary module of my own.

```
[Inline Frame] lua_shared.dll!gc_marktrace(global_State *)
lua_shared.dll!gc_traverse_trace(global_State * g, GCtrace * T)
lua_shared.dll!propagatemark(global_State * g)
[Inline Frame] lua_shared.dll!gc_onestep(lua_State *)
lua_shared.dll!lj_gc_step(lua_State * L)
<any cause of GC here>
```

**Comment by Heavybob** [comment] 2020-04-24 08:24
Any updates here @FredyH ?

**Comment by FredyH** [comment] 2020-04-24 09:51
Hi, I wish I could look into this right now but I am in a hospital at the moment and will probably stay there for quite some time unfortunately (no, not corona). I will maybe try to replicate it but it would probably be better if someone else could look into it.

**Comment by Heavybob** [comment] 2020-04-24 09:54
U better not die, we need this shit fixed. Get well soon.

**Comment by Heavybob** [comment] 2020-06-02 03:18
U still better not be dead and getting well sooner.

**Comment by FredyH** [comment] 2020-06-02 09:59
Not dead yet, I already made some changes (specifically switching back to dynamic linking), that should hopefully fix these crashes some people are experiencing, however this will only be released for 64 bit as MySQL does not make 32 bit clients anymore. Expect that new release soon.

**Comment by Heavybob** [comment] 2020-06-02 10:28
Fantastic. Thanks for not dying.

**Comment by iTzOneLightning** [comment] 2020-06-03 10:00
@FredyH I have the problem on all 3 of my Servers. Wanted to downgrade to 9.5 again, but it doesn't work. So eather way I'm stuck with 9.6 and no mapchanges or nothing. Can you help with the matter of downgrading? I know you're working on a solution for this. Hope you recover soon!

**Comment by FredyH** [comment] 2020-06-03 11:20
If you are running on the 64 bit branch of gmod I could use you to test and see if it is fixed in the new version. If you are interested, add me on Steam: https://steamcommunity.com/id/FredyH

**Comment by iTzOneLightning** [comment] 2020-06-03 13:05
I am! I just added you

**Comment by PieKnu** [comment] 2020-06-12 21:59
I'm having the same issues. But like the others I'm not using GmodAdminSuite.
I got:

- - PointShop2
- - AWarn3
- -mLogs2

**Comment by FredyH** [comment] 2020-06-12 22:45
What operating system?

**Comment by PieKnu** [comment] 2020-06-12 23:02
Oh, it's Ubuntu 18.04.4 LTS 64Bit

**Comment by Synkstar** [comment] 2020-07-17 02:09
My server has issues to I have blogs and it freezes at sending queries to database. This is on a x64 server also had the same issues on x86

**Comment by FredyH** [comment] 2020-07-17 02:16
If it freezes when sending logs that is most likely the fault of blogs, which possibly waits for the query to complete on the main thread

**Comment by Synkstar** [comment] 2020-07-18 01:47
Yeah. Also thanks for making this module btw very useful.

**Comment by FredyH** [comment] 2020-07-18 14:45
According to @Heavybob the crashes have stopped for them since a recent gmod update. Can anyone confirm this?

**Comment by PieKnu** [comment] 2020-07-18 16:58
Totally forgot about this thread. 
But yea, after the last or penultimate GMod update and for me after upgrading & fetching my old TTT Gamemode + changes to the latest one, no crash occurred.

**Comment by FredyH** [comment] 2020-07-20 16:48
Since no one has responded to this with any crashes, I am going to assume that it was indeed a gmod issue. We have not experienced any crashes on the 64 bit branch of gmod in a good while either.

If anyone does still experience this issue, please reopen it.

**Closed by FredyH** 2020-07-20 16:48 UTC
Labels: confirmed
